name: Publish Blazor WebAssembly to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install .NET WebAssembly Tools
      run: dotnet workload install wasm-tools

    - name: Publish Blazor WebAssembly project
      run: dotnet publish src/FateSpin.Client -c Release -o publish

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
      with:
        html_path: publish/wwwroot/index.html
        base_href: /FateSpin/

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: publish/wwwroot

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
